### ISSUE TITLE
typings for use in typescript

### ISSUE THREAD

**Issue by joshua1** [koppa96/linq-extensions#1]
@koppa96 I stumbled upon this project while looking for a linq style extension methods for typescript. Thanks for this first off. I wanted to ask if typings can be included so that this can be used in a typescript project without getting errors such as "property firstOrNull does not exist on type T[]."
Better yet , how best to include in a typescript project so the types are better inferred

**Comment by joshua1** [comment]
Dont worry i figured this out soon after asking by adding to my global.d.ts file the line 
```
/// <reference types="linq-extensions"/>
```
Should have that in the docs

**Comment by koppa96** [comment]
I have not experienced any issue using this in my previous typescript projects, e.g. this angular app:

https://github.com/koppa96/online-computer-shop/blob/master/frontend/webshop/src/app/features/computer-assembler/pages/computer-assembler-page/computer-assembler-page.component.ts

If you import the "linq-extensions" like I did in this file, it should work without any issue. Could you share how exactly did you try to use it?
